In [56]:
from pettingzoo.classic import connect_four_v3
import numpy as np

In [66]:
def is_valid_play(grille, position):
    (i, j) = position
    rows, cols = grille.shape
    # Check nothing above
    if np.all(grille[:i, j] == 0):
        # Check something underneath
        if i == rows - 1 or grille[i+1, j] != 0:
            return True
    else:
        return False

In [11]:
env = connect_four_v3.env()
env.reset()
current_agent = "player_0"
env.agent_selection = current_agent

for x in [0,0,1,1,2,2,0,3,3,4,0,5,5,0,6,5,6]:
    env.step(x)

state = env.observe(agent="player_0")["observation"]
grille = state[:, :, 0] + state[:, :, 1] * 2
grille

array([[0, 0, 0, 0, 0, 0, 0],
       [2, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 2, 0],
       [2, 2, 2, 1, 0, 1, 1],
       [1, 1, 1, 2, 2, 2, 1]], dtype=int8)

In [12]:
def win_row(grille):
    winning_position = [0,1,1,1]
    below = [True for _ in range(grille.shape[1])]
    for i in range(grille.shape[0] - 1, -1, -1):
        for j in range (0,4):
            current_check=grille[i, j:j+4].tolist()
            current_check_ordered = current_check.copy()
            current_check_ordered.sort()
            if current_check_ordered == winning_position:
                if below[current_check.index(0)+j]:
                    return True
        below = [x!=0 for x in grille[i]]
    return False

In [13]:
win_row(grille)

True

In [14]:
env = connect_four_v3.env()
env.reset()
current_agent = "player_0"
env.agent_selection = current_agent

for x in [1,1,1,2,1,4,1]:
    env.step(x)

state = env.observe(agent="player_0")["observation"]
grille = state[:, :, 0] + state[:, :, 1] * 2
grille

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0],
       [0, 1, 2, 0, 2, 0, 0]], dtype=int8)

In [15]:
def win_column(grille):
    for j in range(grille.shape[1]):
        # S'il est possible de jouer dans dans une colonne, on vérifie si il y a victoire direct si on y joue
        if grille[0, j] == 0 and [x for x in grille[:, j] if x != 0, :3] == [1, 1, 1]:
            return True
    return False

In [16]:
win_column(grille)

True

In [75]:
env = connect_four_v3.env()
env.reset()
current_agent = "player_0"
env.agent_selection = current_agent

#for x in [0,1,1,2,2,3,2,5,3,3]:
#    env.step(x)
for x in [0,1,1,2,2,3,2,5,3,1]:
    env.step(x)

state = env.observe(agent="player_0")["observation"]
grille = state[:, :, 0] + state[:, :, 1] * 2
grille

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 2, 1, 0, 0, 0, 0],
       [0, 1, 1, 1, 0, 0, 0],
       [1, 2, 2, 2, 0, 2, 0]], dtype=int8)

In [76]:
def win_diagonal(grille):
    
    rows, cols = grille.shape
    # Vérifie les diagonales montantes
    for i in range(3, rows):
        for j in range(cols - 3):
            n_zeros = 0
            n_ones = 0
            for idx in range(4):
                if grille[i-idx, j+idx] == 1:
                    n_ones += 1
                if grille[i-idx, j+idx] == 0:
                    n_zeros += 1
                    zero_position = (i-idx, j+idx)
            if n_ones == 3 and n_zeros == 1 and is_valid_play(grille, zero_position):
                return True
    # Vérifie les diagonale descendante
    for i in range(rows - 3):
        for j in range(cols - 3):
            n_zeros = 0
            n_ones = 0
            for idx in range(4):
                if grille[i+idx, j+idx] == 1:
                    n_ones += 1
                if grille[i+idx, j+idx] == 0:
                    n_zeros += 1
                    zero_position = (i+idx, j+idx)
            if n_ones == 3 and n_zeros == 1 and is_valid_play(grille, zero_position):
                return True
            
    return False


In [77]:
win_diagonal(grille)

False